export const prompts = [
    "A rainy day that suddenly becomes sunny",
    "Waking up feeling groggy but then remembering it’s your birthday",
    "The feeling you get when you finish homework",
    "Panic turning into relief",
    "A villain slowly realizing they’re losing",
    "Trying to stay calm during a jump scare",
    "Happiness with a tiny hint of chaos",
    "A first crush moment",
    "The calm before a big storm",
    "You just found $20 on the ground",
    "Walking confidently down a hallway like it's a runway",
    "Waiting for the microwave to hit 0",
    "Running late for school",
    "Sneaking cookies at midnight",
    "Turning in an assignment at 11:59 PM",
    "A cat knocking something off a table",
    "Opening a surprise gift",
    "Slipping on a banana peel but recovering coolly",
    "Not knowing if someone waved at you or the person behind you",
    "Accidentally sending a risky text to the wrong person",
    "A knight preparing for battle",
    "A treasure map is found",
    "The monster reveals its true form",
    "Space traveler discovering a new planet",
    "A secret door creaks open",
    "A detective solving the final clue",
    "A ghost trying to be scary but failing",
    "A pirate ship chasing another ship",
    "A wizard casting a chaos spell",
    "Robots slowly gaining sentience",
    "“Bro just said beep boop”",
    "Boss music starts playing out of nowhere",
    "“We have food at home” but the food at home:",
    "POV: You accidentally hit send too early",
    "Someone said “trust me, I’m a professional”",
    "“You didn’t have to cut me off” energy",
    "Dog realizes it's going to the vet",
    "Suspiciously happy elevator music",
    "“I can fix them” energy",
    "Loading screen music that goes TOO HARD",
    "Compose something that must end on a suspenseful note",
    "Start happy, end scary",
    "Make it sound like bouncing",
    "Use only ascending notes",
    "Try to sound like someone is tiptoeing",
    "A song that sounds like it's melting",
    "A countdown but in musical form",
    "A melody that sounds like it's apologizing",
    "A short heroic theme",
    "Something that sounds “drippy”",
    "Dream starts nice then turns weird",
    "Floating in zero gravity",
    "Running in a dream but super slow",
    "Entering a fairy forest",
    "Time loop glitch",
    "You’re made of jelly",
    "Entering a portal to a different timeline",
    "Seeing fireworks underwater",
    "A memory you’re not sure is real",
    "Dancing clouds",
    "A train slowly speeding up",
    "A chase scene through a supermarket",
    "A roller coaster ride",
    "Trying to balance on a tightrope",
    "Jumping on platforms in a video game",
    "Dramatic slow-motion explosion scene",
    "Climbing a mountain",
    "Racing your friend but tripping halfway",
    "Surfing a giant wave",
    "Running away from bees",
    "A chicken trying to look intimidating",
    "A penguin trying to fly but failing",
    "Clown slipping on confetti",
    "A toddler discovering sugar",
    "An evil laugh but in melody form",
    "A fish realizing it’s out of water",
    "A toaster uprising",
    "Someone trying to whistle but can’t",
    "A cow becoming a DJ",
    "A dramatic dramatic... SNEEZE",
    "Entering a magical academy",
    "Casting a forbidden spell",
    "Goblins dancing around a campfire",
    "A dragon waking up",
    "Finding a glowing ancient artifact",
    "A mermaid calling you underwater",
    "Friendly forest spirits",
    "A floating castle appearing in the sky",
    "A shapeshifter changing forms",
    "Nighttime at a wizard’s market",
    "Winning first place by accident",
    "Just barely surviving with 1 HP",
    "Final boss defeated, but there’s Phase 2",
    "Confetti canon misfires",
    "Failing a level with 99% progress",
    "You just leveled up",
    "“New High Score!” energy",
    "You pressed a mysterious red button",
    "Everything is going according to plan… or is it?",
    "End credits roll on a goofy adventure"
]