export const prompts = [
    // ChatGPT
    "A rainy day that suddenly becomes sunny",
    "Waking up feeling groggy but then remembering it's your birthday",
    "The feeling you get when you finish homework",
    "Panic turning into relief",
    "A villain slowly realizing they're losing",
    "Trying to stay calm during a jump scare",
    "Happiness with a tiny hint of chaos",
    "A first crush moment",
    "The calm before a big storm",
    "You just found $20 on the ground",
    "Walking confidently down a hallway like it's a runway",
    "Waiting for the microwave to hit 0",
    "Running late for school",
    "Sneaking cookies at midnight",
    "Turning in an assignment at 11:59 PM",
    "A cat knocking something off a table",
    "Opening a surprise gift",
    "Slipping on a banana peel but recovering coolly",
    "Not knowing if someone waved at you or the person behind you",
    "Accidentally sending a risky text to the wrong person",
    "A knight preparing for battle",
    "A treasure map is found",
    "The monster reveals its true form",
    "Space traveler discovering a new planet",
    "A secret door creaks open",
    "A detective solving the final clue",
    "A ghost trying to be scary but failing",
    "A pirate ship chasing another ship",
    "A wizard casting a chaos spell",
    "Robots slowly gaining sentience",
    "\"Bro just said beep boop\"",
    "Boss music starts playing out of nowhere",
    "\"We have food at home\" but the food at home:",
    "POV: You accidentally hit send too early",
    "Someone said \"trust me, I'm a professional\"",
    "\"You didn't have to cut me off\" energy",
    "Dog realizes it's going to the vet",
    "Suspiciously happy elevator music",
    "\"I can fix them\" energy",
    "Loading screen music that goes TOO HARD",
    "Compose something that must end on a suspenseful note",
    "Start happy, end scary",
    "Make it sound like bouncing",
    "Use only ascending notes",
    "Try to sound like someone is tiptoeing",
    "A song that sounds like it's melting",
    "A countdown but in musical form",
    "A melody that sounds like it's apologizing",
    "A short heroic theme",
    "Something that sounds \"drippy\"",
    "Dream starts nice then turns weird",
    "Floating in zero gravity",
    "Running in a dream but super slow",
    "Entering a fairy forest",
    "Time loop glitch",
    "You're made of jelly",
    "Entering a portal to a different timeline",
    "Seeing fireworks underwater",
    "A memory you're not sure is real",
    "Dancing clouds",
    "A train slowly speeding up",
    "A chase scene through a supermarket",
    "A roller coaster ride",
    "Trying to balance on a tightrope",
    "Jumping on platforms in a video game",
    "Dramatic slow-motion explosion scene",
    "Climbing a mountain",
    "Racing your friend but tripping halfway",
    "Surfing a giant wave",
    "Running away from bees",
    "A chicken trying to look intimidating",
    "A penguin trying to fly but failing",
    "Clown slipping on confetti",
    "A toddler discovering sugar",
    "An evil laugh but in melody form",
    "A fish realizing it's out of water",
    "A toaster uprising",
    "Someone trying to whistle but can't",
    "A cow becoming a DJ",
    "A dramatic dramatic... SNEEZE",
    "Entering a magical academy",
    "Casting a forbidden spell",
    "Goblins dancing around a campfire",
    "A dragon waking up",
    "Finding a glowing ancient artifact",
    "A mermaid calling you underwater",
    "Friendly forest spirits",
    "A floating castle appearing in the sky",
    "A shapeshifter changing forms",
    "Nighttime at a wizard's market",
    "Winning first place by accident",
    "Just barely surviving with 1 HP",
    "Final boss defeated, but there's Phase 2",
    "Confetti canon misfires",
    "Failing a level with 99% progress",
    "You just leveled up",
    "\"New High Score!\" energy",
    "You pressed a mysterious red button",
    "Everything is going according to plan… or is it?",
    "End credits roll on a goofy adventure",
    
    // gemini
    "A slow, creeping doubt",
    "Sudden realization!",
    "A gentle, hopeful sunrise",
    "The feeling of floating",
    "Pure, unadulterated joy",
    "Anxiety starting to build",
    "A melancholic farewell",
    "The sound of quiet contemplation",
    "Rage simmering just below the surface",
    "A secret whispered in the dark",
    "Deep, heavy exhaustion",
    "Finding courage in a hopeless moment",
    "A silly, mischievous grin",
    "Nostalgia for a summer day",
    "Absolute terror",
    "A clumsy giant lumbering by",
    "The graceful dance of a swan",
    "A sneaky, prowling cat",
    "A triumphant hero's return",
    "A shy child hiding behind a curtain",
    "The majestic flight of an eagle",
    "A determined little robot",
    "An annoyed, buzzing bee",
    "The song of an old sea captain",
    "A nervous villain planning a scheme",
    "The footsteps of a phantom",
    "A friendly alien greeting",
    "A royal fanfare for a tiny dog",
    "A ghost trying to sing",
    "A wizard brewing a potion",
    "Walking through a bustling marketplace",
    "The quiet of a deep forest",
    "A theme for a forgotten city",
    "The wild, rolling ocean waves",
    "Exploring a dark, winding cave",
    "The view from a tall mountain peak",
    "A peaceful, hidden meadow",
    "Traffic in a busy city street",
    "The bells of an ancient clock tower",
    "Underneath a starry desert sky",
    "A theme park's happy entrance",
    "A secret garden gate opening",
    "The quiet of an empty library",
    "A boat gently rocking on a lake",
    "Inside a spooky, abandoned house",
    "A jump over a tiny puddle",
    "Running away from something scary",
    "A slow-motion stumble",
    "The process of patiently waiting",
    "Building a very tall tower",
    "A dramatic, sudden stop",
    "A silly attempt at juggling",
    "The moment a balloon pops",
    "Tiptoeing past a sleeping guard",
    "A series of three quick knocks",
    "Pushing a heavy rock uphill",
    "Unwrapping a wonderful present",
    "A chase scene across rooftops",
    "Waking up suddenly from a dream",
    "The climax of a cooking show",
    "Bouncing a rubber ball",
    "A short, circular melody",
    "The sound of a dripping faucet",
    "An ascending alarm clock",
    "The rhythm of a heart beat",
    "A small, shiny key",
    "The color Red",
    "A melody played only on black keys",
    "A four-note question",
    "A series of three high notes",
    "A low, sustained drone",
    "A skipping rope rhyme",
    "The ticking of a stopwatch",
    "A melody that goes up, then immediately down",
    "A musical sigh",
    "Picking up a powerful item",
    "Leveling up!",
    "The final boss theme's intro",
    "Running out of time",
    "A secret passageway revealed",
    "The main village theme",
    "Losing a life",
    "Discovering a treasure chest",
    "An underwater swimming sequence",
    "The end-of-level victory jingle",
    "The sound of \"Oops, I forgot my keys!\"",
    "A melody that sounds like a question mark",
    "The most boring theme song ever",
    "A short burst of inspiration",
    "The jingle for a terrible product",
    "A sequence that makes you scrunch your face",
    "Music that sounds like a sneeze",
    "A melody played in reverse",
    "A musical shrug",
    "The theme for an imaginary vegetable",
    "The sound a banana makes when peeled",
    "A very bad attempt at a scale",
    "The musical equivalent of a groan",
    "A song that is always getting louder",
    "The noise of a dropped coin",

    // Claude
    "Happy Birthday",
    "Twinkle Twinkle Little Star",
    "Mary Had a Little Lamb",
    "Row Row Row Your Boat",
    "Jingle Bells (chorus)",
    "Amazing Grace (first line)",
    "Ode to Joy",
    "We Wish You a Merry Christmas",
    "London Bridge Is Falling Down",
    "The Wheels on the Bus",
    "We Will Rock You (stomp stomp clap)",
    "Seven Nation Army (opening riff)",
    "Smoke on the Water (guitar riff)",
    "Imperial March (Star Wars)",
    "Pink Panther Theme",
    "Mission Impossible Theme",
    "Tetris Theme (A-Theme)",
    "Super Mario Bros Theme",
    "Zelda Main Theme",
    "Eye of the Tiger (opening)",
    "Do-Re-Mi-Fa-So ascending",
    "So-Fa-Mi-Re-Do descending",
    "C major arpeggio (C-E-G-C)",
    "Blues scale riff",
    "Chromatic scale up 5 notes",
    "Pentatonic melody",
    "Simple call and response",
    "Three note descending pattern",
    "Bouncing octaves",
    "Zigzag pattern (up-down-up-down)",
    "James Bond Theme",
    "Jurassic Park Theme",
    "Harry Potter Theme (Hedwig's Theme)",
    "The Simpsons Theme",
    "Game of Thrones Theme",
    "Indiana Jones Theme",
    "Back to the Future Theme",
    "E.T. Theme",
    "Jaws Theme (two notes!)",
    "The Office Theme",
    "Deck the Halls",
    "Silent Night",
    "Rudolph the Red-Nosed Reindeer",
    "Frosty the Snowman",
    "O Christmas Tree",
    "Jingle Bell Rock (opening)",
    "Santa Claus Is Coming to Town",
    "Let It Snow",
    "Winter Wonderland",
    "The Dreidel Song",
    "Itsy Bitsy Spider",
    "Old MacDonald Had a Farm",
    "BINGO",
    "If You're Happy and You Know It",
    "The Alphabet Song",
    "Five Little Monkeys",
    "Head Shoulders Knees and Toes",
    "This Old Man",
    "Pop Goes the Weasel",
    "Hickory Dickory Dock",
    "Für Elise (opening)",
    "Canon in D (opening)",
    "Moonlight Sonata (first phrase)",
    "Turkish March",
    "Eine Kleine Nachtmusik",
    "Spring (Vivaldi's Four Seasons)",
    "Toreador Song (Carmen)",
    "William Tell Overture (finale)",
    "Ride of the Valkyries",
    "Dance of the Sugar Plum Fairy",
    "Star Spangled Banner (opening)",
    "God Save the Queen/King",
    "La Marseillaise (opening)",
    "O Canada",
    "Yankee Doodle",
    "America the Beautiful",
    "My Country Tis of Thee",
    "This Land Is Your Land",
    "Stars and Stripes Forever",
    "Battle Hymn of the Republic",
    "Cha Cha Slide (melody)",
    "Macarena (chorus)",
    "YMCA (chorus melody)",
    "Celebration (chorus)",
    "Stayin' Alive (opening)",
    "Dancing Queen (chorus)",
    "Don't Stop Believin' (opening piano)",
    "Sweet Caroline (ba ba ba!)",
    "Hey Jude (na na na section)",
    "Livin' on a Prayer (whoa-oh!)",
    "Ice cream truck jingle",
    "Nokia ringtone",
    "Doorbell chime",
    "Happy birthday but jazzy",
    "Funeral march",
    "Wedding march (Here Comes the Bride)",
    "Reveille (wake up call)",
    "Taps (military)",
    "Shave and a Haircut",
    "Charge! (sports stadium)",

    // Grok
    "Create a cheerful melody for a sunny morning walk.",
    "Compose a spooky tune for a haunted house scene.",
    "Craft a heroic anthem for a superhero's victory.",
    "Build a dreamy lullaby for a starry night.",
    "Make a fast-paced melody for a car chase.",
    "Design a romantic tune for a sunset beach stroll.",
    "Create a mysterious melody for a detective solving a case.",
    "Compose a bouncy song for a children's playground.",
    "Craft a somber tune for a rainy day indoors.",
    "Make an epic melody for a fantasy battle.",
    "Create a funky groove for a disco dance floor.",
    "Build a serene melody for a peaceful forest.",
    "Compose a tense tune for a thriller movie climax.",
    "Craft a nostalgic song for a childhood memory.",
    "Make a jazzy melody for a late-night city vibe.",
    "Create a hopeful tune for a new beginning.",
    "Compose a chaotic melody for a bustling market.",
    "Build a magical tune for a wizard's spell-casting.",
    "Craft a playful melody for a puppy chasing its tail.",
    "Make a dramatic song for a theater curtain reveal.",
    "Create a futuristic melody for a sci-fi spaceship launch.",
    "Compose a calming tune for a meditation session.",
    "Build a triumphant melody for winning a race.",
    "Craft a quirky song for a cartoon character's adventure.",
    "Make a melancholic tune for a farewell scene.",
    "Create an energetic melody for a sports montage.",
    "Compose a mystical tune for an ancient ruins exploration.",
    "Build a groovy melody for a 1970s dance party.",
    "Craft a suspenseful tune for a horror movie jump scare.",
    "Make a whimsical song for a fairy tale forest.",
    "Create a bold melody for a knight's quest.",
    "Compose a soothing tune for an ocean wave scene.",
    "Build an intense melody for a boxing match.",
    "Craft a joyful song for a family reunion.",
    "Make a mysterious melody for a secret agent mission.",
    "Create a vibrant tune for a festival celebration.",
    "Compose a haunting melody for a ghost story.",
    "Build a rhythmic song for a street drummer's performance.",
    "Craft a tender melody for a love confession.",
    "Make an adventurous tune for a jungle expedition.",
    "Create a quirky melody for a mad scientist's lab.",
    "Compose a hopeful song for a sunrise scene.",
    "Build a dramatic melody for a storm at sea.",
    "Craft a playful tune for a snowball fight.",
    "Make a soulful melody for a late-night blues jam.",
    "Create an uplifting song for a graduation ceremony.",
    "Compose a sneaky tune for a cat burglar's heist.",
    "Build a majestic melody for a royal coronation.",
    "Craft a cozy song for a winter fireplace scene.",
    "Make a vibrant melody for a carnival parade.",
    "Create a melancholic tune for an autumn leaf fall.",
    "Compose an eerie melody for a foggy graveyard.",
    "Build a lively song for a street dance battle.",
    "Craft a serene tune for a mountain sunrise.",
    "Make a thrilling melody for a rollercoaster ride.",
    "Create a heartfelt song for a soldier's homecoming.",
    "Compose a quirky tune for a robot's daily routine.",
    "Build a magical melody for a unicorn's gallop.",
    "Craft a tense song for a courtroom drama.",
    "Make a cheerful melody for a picnic in the park.",
    "Create a futuristic tune for a virtual reality world.",
    "Compose a gentle melody for a baby's first steps.",
    "Build a bold song for a revolutionary speech.",
    "Craft a spooky tune for a midnight forest walk.",
    "Make an upbeat melody for a summer road trip.",
    "Create a mystical song for a dragon's flight.",
    "Compose a romantic tune for a ballroom dance.",
    "Build a chaotic melody for a clown's circus act.",
    "Craft a hopeful melody for a charity event.",
    "Make a groovy song for a retro arcade game.",
    "Create a somber tune for a memorial service.",
    "Compose a lively melody for a salsa dance party.",
    "Build a dramatic song for a volcano eruption.",
    "Craft a whimsical tune for a fairy's flight.",
    "Make a suspenseful melody for a treasure hunt.",
    "Create an energetic song for a marathon finish line.",
    "Compose a dreamy tune for a moonlit lake.",
    "Build a funky melody for a skateboarder's tricks.",
    "Craft a majestic song for a lion's roar.",
    "Make a playful tune for a kitten's pounce.",
    "Create a heroic melody for a firefighter's rescue.",
    "Compose a serene song for a Zen garden.",
    "Build a thrilling tune for a skydiving adventure.",
    "Craft a nostalgic melody for a vintage radio.",
    "Make a mysterious song for an alien encounter.",
    "Create a joyful tune for a wedding dance.",
    "Compose a haunting melody for an abandoned mansion.",
    "Build a rhythmic song for a tap dance routine.",
    "Craft a tender tune for a mother's lullaby.",
    "Make an epic melody for a space battle.",
    "Create a quirky song for a time traveler's journey.",
    "Compose a vibrant tune for a street festival.",
    "Build a somber melody for a soldier's sacrifice.",
    "Craft a lively song for a beach volleyball game.",
    "Make a magical tune for a wizard's duel.",
    "Create a hopeful melody for a community rebuild.",
    "Compose a sneaky song for a fox in the woods.",
    "Build a dramatic melody for a shipwreck discovery.",
    "Craft a cheerful tune for a farmer's market.",
    "Make a futuristic song for a robot uprising.",

    // Deepseek
    "A tiny robot learning to whistle.",
    "A raindrop's journey down a window pane.",
    "A sleepy cat stretching in a sunbeam.",
    "A bouncing ball in a slow-motion video.",
    "A butterfly fluttering through a garden.",
    "A ghost trying to hum a forgotten lullaby.",
    "A single firefly blinking in the dark.",
    "A teapot coming to a boil.",
    "A snowflake drifting to the ground.",
    "A ladybug climbing up a blade of grass.",
    "The first drops of a gentle spring rain.",
    "A secret conversation between two crickets.",
    "Wind chimes on a breezy porch.",
    "A babbling brook trickling over stones.",
    "The lonely call of a distant loon on a lake.",
    "The Northern Lights dancing in the sky.",
    "A volcano grumbling before it erupts.",
    "The deep, slow pulse of the ocean's tide.",
    "A forest waking up at dawn.",
    "The sound of a geyser shooting into the air.",
    "The happy skip in your step when you're in love.",
    "The heavy, slow melody of loneliness.",
    "The frantic, chaotic sound of anxiety.",
    "The warm, cozy feeling of nostalgia.",
    "The triumphant fanfare of achieving a small victory.",
    "The curious and playful tune of discovery.",
    "The bittersweet melody of a last goodbye.",
    "The lazy, hazy feeling of a summer afternoon.",
    "The spark of a brilliant new idea.",
    "The soothing rhythm of a calm, steady heartbeat.",
    "A grumpy troll stomping under a bridge.",
    "A mischievous fairy playing a prank.",
    "A wise old owl's nightly soliloquy.",
    "A clumsy giant trying to tiptoe.",
    "A sly fox sneaking through the undergrowth.",
    "A lonely space robot sending a signal home.",
    "A mermaid singing a siren's call.",
    "A knight's noble theme as they ride into battle.",
    "A wizard casting a slightly faulty spell.",
    "A curious alien observing Earth for the first time.",
    "Typing a very important letter on an old typewriter.",
    "Popcorn popping in a microwave.",
    "A pinball machine's ricocheting melody.",
    "The sound of a city street from ten stories up.",
    "A clock ticking down the final minute.",
    "The frantic search for lost keys.",
    "A slow-motion dive into a swimming pool.",
    "Building a house of cards.",
    "The satisfying click of a puzzle piece fitting in.",
    "A rocket's countdown and launch sequence.",
    "An old, slightly out-of-tune music box.",
    "A dial-up modem connecting to the internet.",
    "A creaky windmill turning in the field.",
    "The engine of a classic car starting up.",
    "A computer processing a very complex calculation.",
    "A leaky faucet in an empty house.",
    "A grandfather clock striking midnight.",
    "The hum of a refrigerator in the middle of the night.",
    "A photocopier scanning a document.",
    "The startup chime of a vintage computer.",
    "The opening theme for a magical library.",
    "A map that comes to life and sings its directions.",
    "The spell to unlock an ancient, hidden door.",
    "A lullaby sung to a baby dragon.",
    "The theme for the world's most relaxed knight.",
    "The sound of a memory being erased.",
    "A message in a bottle, translated into music.",
    "The melody of a forgotten constellation.",
    "The soundtrack to a dream about flying.",
    "The quiet magic of a hidden glen.",
    "The color blue, as a sound.",
    "The feeling of deja vu.",
    "The sound of silence.",
    "The texture of rough sandpaper.",
    "The taste of a sour lemon.",
    "The weightlessness of zero gravity.",
    "The concept of \"yesterday.\"",
    "The smell of rain on hot asphalt (petrichor).",
    "The sound of a shadow moving.",
    "The feeling of a gentle, warm breeze.",
    "A lonely satellite orbiting Earth.",
    "The hustle and bustle of a neon-lit cyberpunk street.",
    "The quiet, solemn atmosphere of an empty cathedral.",
    "A busy ant colony underground.",
    "The inside of a kaleidoscope.",
    "A secret base inside a volcano.",
    "A bustling port with ships and seagulls.",
    "The calm of a Japanese zen garden.",
    "A data stream flowing through the internet.",
    "A dusty, forgotten attic full of treasures.",
    "A spaghetti noodle trying to be a violin string.",
    "A sock that's lost its pair, singing the blues.",
    "A confused chicken who thinks it's a composer.",
    "The sound of a yawn contagiousness spreading.",
    "A dance party for garden gnomes.",
    "A conversation between two talking belly buttons.",
    "The triumphant march of a rubber duck army.",
    "The sound of a thought bubble popping.",
    "A snail's heavy metal power ballad.",
    "The theme song for a sentient, slightly-melancholy loaf of bread.",

    // Perplexity
    "A tune that feels like falling in love",
    "The sound of heartbreak in slow motion",
    "Music for waking up after a perfect daydream",
    "A song that sounds like missing someone",
    "The sound of hope returning",
    "A melody that feels like pure nostalgia",
    "The panic before an exam in song form",
    "A lullaby for grown-ups",
    "The soundtrack to forgiving someone",
    "A melody that slowly turns from happy to sad",
    "Music for a rainy afternoon in Paris",
    "The tune of a desert sunset",
    "What a forest sounds like at midnight",
    "A song from a ghost town's last night",
    "What the ocean hums to itself",
    "The sound of morning traffic in Tokyo",
    "The melody of a carnival closing down",
    "A tune for walking through snowfall",
    "The sound of space when no one's around",
    "What your childhood street might sing",
    "The theme song for a shy superhero",
    "Music for a villain who changes sides",
    "A melody a robot might compose after feeling emotions",
    "The opening theme for a detective pigeon",
    "The song a dragon hums while hoarding gold",
    "The tune a time traveler plays while lost",
    "A lullaby sung by an alien to its child",
    "The anthem of an underwater kingdom",
    "The rhythm of a mischievous cat's adventure",
    "The victory song of an underdog hero",
    "A spell that turns day into night",
    "The melody of a potion gone wrong",
    "The background music of a fairy forest",
    "The sound of an enchanted mirror",
    "The tune of two wizards dueling",
    "The theme of a magical bakery",
    "A song to summon rainbows",
    "The chant of dancing spirits",
    "A lullaby for a sleeping volcano",
    "The anthem of clouds drifting away",
    "What a chicken's workout song might sound like",
    "A melody about forgetting your password",
    "Music for brushing your teeth heroically",
    "A tune that sounds like someone lost in IKEA",
    "The national anthem of socks that disappear in the dryer",
    "A song you'd hear in a fridge rave",
    "The theme of a potato on vacation",
    "Elevator music for a spaceship",
    "The sound of accidentally opening 100 tabs",
    "A sad jingle for an overworked printer",
    "A melody that starts sleepy but becomes heroic",
    "The transformation of a caterpillar in sound",
    "The rise and fall of a mythical city",
    "An echo of an ancient celebration",
    "A tune that watches stars being born",
    "Music that sounds like growing up",
    "The soundtrack to a breakup text",
    "A melody that ends before the story does",
    "The life cycle of a snowflake in tune form",
    "A duet between thunder and silence",
    "A boss fight song for a cute enemy",
    "The theme of a chill video game shop",
    "Victory music after eating your last life fruit",
    "What an 8-bit sunrise sounds like",
    "Level-up music that's slightly out of key",
    "The soundtrack of a pixelated galaxy",
    "The song your game character hums while idle",
    "Background music for a stealth mission gone wrong",
    "The jingle for a fake mobile game ad",
    "Battle theme for two rival pizza chefs",
    "Turn a lullaby into a rock riff",
    "Make a waltz sound spooky",
    "Write a blues tune for robots",
    "Imagine a pop ballad without lyrics",
    "A classical symphony about chaos",
    "A techno beat that narrates jealousy",
    "A reggae melody about the moon",
    "A folk song from a tiny island nation",
    "A minimalist jazz phrase about confusion",
    "A medieval tune for modern hearts",
    "Music that describes “time melting”",
    "The sound of a secret being revealed",
    "What déjà vu might sound like",
    "The feeling of falling upwards",
    "The sound of an unopened letter",
    "A melody that almost remembers itself",
    "A tune that loops like a dream",
    "Soundtrack to a lost memory",
    "A melody that keeps changing colors",
    "The echo of something never heard",
    "A melody for New Year's Day before sunrise",
    "The sound of Halloween night from a pumpkin's view",
    "A tune that tastes like gingerbread",
    "The song fireworks would play",
    "An anthem for a festival of light",
    "Music for the first day of spring",
    "A melody to welcome the new year on Mars",
    "The sound of wrapping a perfect gift",
    "The tune of a cozy winter dinner",
    "What love would sound like on Valentine's Night"
]